# yamllint configuration
# Used by pre-commit and CI

---
extends: default

rules:
  line-length:
    max: 200
    level: warning

  document-start: disable

  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1

  indentation:
    spaces: 2
    indent-sequences: whatever

  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  empty-values: disable

  new-line-at-end-of-file: disable
